# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StatePreservation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StatePreservation

  pod 'Alamofire', '~> 5.1'
  target 'StatePreservationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
